version: '3.3'

services:
  
  opendata-crawler:
    container_name: opendata-crawler
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile
    image: opendata-crawler:1.0.0
    user: root
    volumes:
      - /dev/crawler-ei2a/src/main/python:/app:cached
    restart: always
    environment:
      TZ: Europe/Madrid
      LOGLEVEL: DEBUG
    logging:
      driver: journald
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    security_opt:
      - seccomp=unconfined
    network_mode: "host"
   
